apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: default
spec:
  containers:
  - image: thinhar/blenderworker:1.21
    name: temp
    tty: true
  serviceAccount: pod-creation-sa
  serviceAccountName: pod-creation-sa
