
apiVersion: v1
kind: ServiceAccount
metadata:
 name: pod-creation-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-creator
  namespace: default
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['get','create','watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-creator-binding
  namespace: default
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pod-creation-sa
  namespace: default
